services:
  - type: web
    name: carbonbyte
    runtime: python
    repo: https://github.com/AnneLovina/carbonbyte
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key PORT
        value: 8080
      - key: SECRET_KEY
        generateValue: true # Generates a secure secret key automatically
 
    buildCommand: |
      pip install --upgrade pip
      pip install gunicorn # Add gunicorn for production
      pip install -r requirements.txt
    startCommand: gunicorn app:app 
    plan: free 
    autoDeploy: true 
